### PR TITLE
Fix flush race condition

### LINKED ISSUE #82: Test flushing of remaining buffer in _final
https://github.com/Level/level-ws/blob/182314539e46f1b0c056a622c676612ad005b447/level-ws.js#L89-L92

Lines 90-91 are [not covered atm](https://coveralls.io/builds/17764743/source?filename=level-ws.js#L90).

### PR DESCRIPTION
**Pull request by vweevers**
Described in https://github.com/Level/level-ws/issues/82#issuecomment-401527100. As luck would have it, this fix (and test) trigger a flush in `_final`, which is what I initially set out to do in #82. So closes #82.

### CODE REVIEW

File: level-ws.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ WriteStream.prototype._write = function (d, enc, next) {
       self._buffer.length > self._options.maxBufferLength) {
     self.once('_flush', next)
   } else {
-    if (self._buffer.length === 0) {
+    if (!self._flushing) {
```
Comment (ralphtheninja) [inline level-ws.js]: This makes more sense too, that you check the boolean and if not set, you set it and do stuff.

Comment (vweevers) [reply level-ws.js]: Yea. Can you think of any negative consequences?

Comment (ralphtheninja) [reply level-ws.js]: And I was wrong about 2. This is the simplest fix.

Comment (vweevers) [reply level-ws.js]: > Can you think of any negative consequences?

`level-ws` isn't advertised as a performant writestream so I guess we're fine
