### PR TITLE
Fix race condition by flushing before finish

### LINKED ISSUE #10: Race conditions
discovered two race conditions running the tests on node 3:

```
TAP version 13
# test simple WriteStream
ok 1 no error
ok 2 no error
ok 3 not writable
ok 4 not readable
ok 5 no error
ok 6 WriteStream data #0 has correct value
ok 7 no error
ok 8 WriteStream data #1 has correct value
ok 9 no error
ok 10 WriteStream data #2 has correct value
ok 11 no error
ok 12 WriteStream data #3 has correct value
ok 13 no error
ok 14 WriteStream data #4 has correct value
ok 15 no error
ok 16 WriteStream data #5 has correct value
ok 17 no error
ok 18 WriteStream data #6 has correct value
ok 19 no error
ok 20 WriteStream data #7 has correct value
ok 21 no error
ok 22 WriteStream data #8 has correct value
ok 23 no error
ok 24 WriteStream data #9 has correct value
# test WriteStream with async writes
ok 25 no error
ok 26 no error
ok 27 not writable
ok 28 not readable
ok 29 no error
ok 30 WriteStream data #0 has correct value
ok 31 no error
ok 32 WriteStream data #1 has correct value
ok 33 no error
ok 34 WriteStream data #2 has correct value
ok 35 no error
ok 36 WriteStream data #3 has correct value
ok 37 no error
ok 38 WriteStream data #4 has correct value
ok 39 no error
ok 40 WriteStream data #5 has correct value
ok 41 no error
ok 42 WriteStream data #6 has correct value
ok 43 no error
ok 44 WriteStream data #7 has correct value
ok 45 no error
ok 46 WriteStream data #8 has correct value
ok 47 no error
ok 48 WriteStream data #9 has correct value
# test end accepts data
ok 49 no error
ok 50 no error
ok 51 not writable
ok 52 not readable
ok 53 no error
ok 54 WriteStream data #0 has correct value
ok 55 no error
ok 56 WriteStream data #1 has correct value
ok 57 no error
ok 58 WriteStream data #2 has correct value
ok 59 no error
ok 60 WriteStream data #3 has correct value
ok 61 no error
ok 62 WriteStream data #4 has correct value
ok 63 no error
ok 64 WriteStream data #5 has correct value
ok 65 no error
ok 66 WriteStream data #6 has correct value
ok 67 no error
ok 68 WriteStream data #7 has correct value
ok 69 no error
ok 70 WriteStream data #8 has correct value
ok 71 no error
ok 72 WriteStream data #9 has correct value
# test destroySoon()
ok 73 no error
ok 74 no error
ok 75 not writable
ok 76 not readable
ok 77 no error
ok 78 WriteStream data #0 has correct value
ok 79 no error
ok 80 WriteStream data #1 has correct value
ok 81 no error
ok 82 WriteStream data #2 has correct value
ok 83 no error
ok 84 WriteStream data #3 has correct value
ok 85 no error
ok 86 WriteStream data #4 has correct value
ok 87 no error
ok 88 WriteStream data #5 has correct value
ok 89 no error
ok 90 WriteStream data #6 has correct value
ok 91 no error
ok 92 WriteStream data #7 has correct value
ok 93 no error
ok 94 WriteStream data #8 has correct value
ok 95 no error
ok 96 WriteStream data #9 has correct value
# test destroy()
ok 97 no error
ok 98 no error
ok 99 is writable
ok 100 not readable
ok 101 is writable
ok 102 not readable
ok 103 is writable
ok 104 not readable
ok 105 is writable
ok 106 not readable
ok 107 is writable
ok 108 not readable
ok 109 is writable
ok 110 not readable
ok 111 is writable
ok 112 not readable
ok 113 is writable
ok 114 not readable
ok 115 is writable
ok 116 not readable
ok 117 is writable
ok 118 not readable
ok 119 is writable
ok 120 not readable
ok 121 is writable
ok 122 not readable
ok 123 not writable
ok 124 got expected error
ok 125 did not get value
ok 126 got expected error
ok 127 did not get value
ok 128 got expected error
ok 129 did not get value
ok 130 got expected error
ok 131 did not get value
ok 132 got expected error
ok 133 did not get value
ok 134 got expected error
ok 135 did not get value
ok 136 got expected error
ok 137 did not get value
ok 138 got expected error
ok 139 did not get value
ok 140 got expected error
ok 141 did not get value
ok 142 got expected error
ok 143 did not get value
# test json encoding
ok 144 no error
ok 145 no error
ok 146 not writable
ok 147 not readable
not ok 148 no error
  ---
    operator: notOk
    expected: false
    actual:   {}
    at: dispatchError (/home/travis/build/Level/level-ws/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/util.js:64:35)
  ...
not ok 149 WriteStream data #aa has correct value
  ---
    operator: equal
    expected: NaN
    actual:   NaN
    at: dispatchError (/home/travis/build/Level/level-ws/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/util.js:64:35)
  ...
ok 150 no error
ok 151 WriteStream data #ab has correct value
ok 152 no error
ok 153 WriteStream data #ac has correct value
ok 154 no error
ok 155 WriteStream data #ba has correct value
ok 156 no error
ok 157 WriteStream data #bb has correct value
ok 158 no error
ok 159 WriteStream data #bc has correct value
ok 160 no error
ok 161 WriteStream data #ca has correct value
ok 162 no error
ok 163 WriteStream data #cb has correct value
ok 164 no error
ok 165 WriteStream data #cc has correct value
# test del capabilities for each key/value
ok 166 no error
ok 167 no error
ok 168 got expected error
ok 169 did not get value
ok 170 got expected error
ok 171 did not get value
ok 172 got expected error
ok 173 did not get value
ok 174 got expected error
ok 175 did not get value
ok 176 got expected error
ok 177 did not get value
ok 178 got expected error
ok 179 did not get value
ok 180 got expected error
ok 181 did not get value
ok 182 got expected error
ok 183 did not get value
ok 184 got expected error
ok 185 did not get value
# test del capabilities as constructor option
ok 186 no error
ok 187 no error
ok 188 got expected error
ok 189 did not get value
ok 190 got expected error
ok 191 did not get value
ok 192 got expected error
ok 193 did not get value
ok 194 got expected error
ok 195 did not get value
ok 196 got expected error
ok 197 did not get value
ok 198 got expected error
ok 199 did not get value
ok 200 got expected error
ok 201 did not get value
ok 202 got expected error
ok 203 did not get value
ok 204 got expected error
ok 205 did not get value
# test type at key/value level must take precedence on the constructor
ok 206 no error
ok 207 no error
ok 208 got value
ok 209 got expected error
ok 210 did not get value
ok 211 got expected error
ok 212 did not get value
ok 213 got expected error
ok 214 did not get value
ok 215 got expected error
ok 216 did not get value
ok 217 got expected error
ok 218 did not get value
ok 219 got expected error
ok 220 did not get value
ok 221 got expected error
ok 222 did not get value
ok 223 got expected error
ok 224 did not get value
# test ignoring pairs with the wrong type
ok 225 no error
ok 226 no error
ok 227 got expected error
ok 228 did not get value
ok 229 got expected error
ok 230 did not get value
ok 231 got expected error
ok 232 did not get value
ok 233 got expected error
ok 234 did not get value
ok 235 got expected error
ok 236 did not get value
ok 237 got expected error
ok 238 did not get value
ok 239 got expected error
ok 240 did not get value
ok 241 got expected error
ok 242 did not get value
ok 243 got expected error
ok 244 did not get value
ok 245 got expected error
ok 246 did not get value

1..246
# tests 246
# pass  244
# fail  2
```

```
TAP version 13
# test simple WriteStream
ok 1 no error
ok 2 no error
ok 3 not writable
ok 4 not readable
ok 5 no error
ok 6 WriteStream data #0 has correct value
ok 7 no error
ok 8 WriteStream data #1 has correct value
ok 9 no error
ok 10 WriteStream data #2 has correct value
ok 11 no error
ok 12 WriteStream data #3 has correct value
ok 13 no error
ok 14 WriteStream data #4 has correct value
ok 15 no error
ok 16 WriteStream data #5 has correct value
ok 17 no error
ok 18 WriteStream data #6 has correct value
ok 19 no error
ok 20 WriteStream data #7 has correct value
ok 21 no error
ok 22 WriteStream data #8 has correct value
ok 23 no error
ok 24 WriteStream data #9 has correct value
# test WriteStream with async writes
ok 25 no error
ok 26 no error
ok 27 not writable
ok 28 not readable
ok 29 no error
ok 30 WriteStream data #0 has correct value
ok 31 no error
ok 32 WriteStream data #1 has correct value
ok 33 no error
ok 34 WriteStream data #2 has correct value
ok 35 no error
ok 36 WriteStream data #3 has correct value
ok 37 no error
ok 38 WriteStream data #4 has correct value
ok 39 no error
ok 40 WriteStream data #5 has correct value
ok 41 no error
ok 42 WriteStream data #6 has correct value
ok 43 no error
ok 44 WriteStream data #7 has correct value
ok 45 no error
ok 46 WriteStream data #8 has correct value
ok 47 no error
ok 48 WriteStream data #9 has correct value
# test end accepts data
ok 49 no error
ok 50 no error
ok 51 not writable
ok 52 not readable
ok 53 no error
ok 54 WriteStream data #0 has correct value
ok 55 no error
ok 56 WriteStream data #1 has correct value
ok 57 no error
ok 58 WriteStream data #2 has correct value
ok 59 no error
ok 60 WriteStream data #3 has correct value
ok 61 no error
ok 62 WriteStream data #4 has correct value
ok 63 no error
ok 64 WriteStream data #5 has correct value
ok 65 no error
ok 66 WriteStream data #6 has correct value
ok 67 no error
ok 68 WriteStream data #7 has correct value
ok 69 no error
ok 70 WriteStream data #8 has correct value
ok 71 no error
ok 72 WriteStream data #9 has correct value
# test destroySoon()
ok 73 no error
ok 74 no error
ok 75 not writable
ok 76 not readable
ok 77 no error
ok 78 WriteStream data #0 has correct value
ok 79 no error
ok 80 WriteStream data #1 has correct value
ok 81 no error
ok 82 WriteStream data #2 has correct value
ok 83 no error
ok 84 WriteStream data #3 has correct value
ok 85 no error
ok 86 WriteStream data #4 has correct value
ok 87 no error
ok 88 WriteStream data #5 has correct value
ok 89 no error
ok 90 WriteStream data #6 has correct value
ok 91 no error
ok 92 WriteStream data #7 has correct value
ok 93 no error
ok 94 WriteStream data #8 has correct value
ok 95 no error
ok 96 WriteStream data #9 has correct value
# test destroy()
ok 97 no error
ok 98 no error
ok 99 is writable
ok 100 not readable
ok 101 is writable
ok 102 not readable
ok 103 is writable
ok 104 not readable
ok 105 is writable
ok 106 not readable
ok 107 is writable
ok 108 not readable
ok 109 is writable
ok 110 not readable
ok 111 is writable
ok 112 not readable
ok 113 is writable
ok 114 not readable
ok 115 is writable
ok 116 not readable
ok 117 is writable
ok 118 not readable
ok 119 is writable
ok 120 not readable
ok 121 is writable
ok 122 not readable
ok 123 not writable
ok 124 got expected error
ok 125 did not get value
ok 126 got expected error
ok 127 did not get value
ok 128 got expected error
ok 129 did not get value
ok 130 got expected error
ok 131 did not get value
ok 132 got expected error
ok 133 did not get value
ok 134 got expected error
ok 135 did not get value
ok 136 got expected error
ok 137 did not get value
ok 138 got expected error
ok 139 did not get value
ok 140 got expected error
ok 141 did not get value
ok 142 got expected error
ok 143 did not get value
# test json encoding
ok 144 no error
ok 145 no error
ok 146 not writable
ok 147 not readable
ok 148 no error
ok 149 WriteStream data #aa has correct value
ok 150 no error
ok 151 WriteStream data #ab has correct value
ok 152 no error
ok 153 WriteStream data #ac has correct value
ok 154 no error
ok 155 WriteStream data #ba has correct value
ok 156 no error
ok 157 WriteStream data #bb has correct value
ok 158 no error
ok 159 WriteStream data #bc has correct value
ok 160 no error
ok 161 WriteStream data #ca has correct value
ok 162 no error
ok 163 WriteStream data #cb has correct value
ok 164 no error
ok 165 WriteStream data #cc has correct value
# test del capabilities for each key/value
ok 166 no error
ok 167 no error
not ok 168 got expected error
  ---
    operator: ok
    expected: true
    actual:   null
  ...
not ok 169 did not get value
  ---
    operator: notOk
    expected: |-
      false
    actual: |-
      { a: 'complex', obj: 100 }
  ...
ok 170 got expected error
ok 171 did not get value
ok 172 got expected error
ok 173 did not get value
ok 174 got expected error
ok 175 did not get value
ok 176 got expected error
ok 177 did not get value
ok 178 got expected error
ok 179 did not get value
ok 180 got expected error
ok 181 did not get value
ok 182 got expected error
ok 183 did not get value
ok 184 got expected error
ok 185 did not get value
# test del capabilities as constructor option
ok 186 no error
ok 187 no error
ok 188 got expected error
ok 189 did not get value
ok 190 got expected error
ok 191 did not get value
ok 192 got expected error
ok 193 did not get value
ok 194 got expected error
ok 195 did not get value
ok 196 got expected error
ok 197 did not get value
ok 198 got expected error
ok 199 did not get value
ok 200 got expected error
ok 201 did not get value
ok 202 got expected error
ok 203 did not get value
ok 204 got expected error
ok 205 did not get value
# test type at key/value level must take precedence on the constructor
ok 206 no error
ok 207 no error
ok 208 got value
ok 209 got expected error
ok 210 did not get value
ok 211 got expected error
ok 212 did not get value
ok 213 got expected error
ok 214 did not get value
ok 215 got expected error
ok 216 did not get value
ok 217 got expected error
ok 218 did not get value
ok 219 got expected error
ok 220 did not get value
ok 221 got expected error
ok 222 did not get value
ok 223 got expected error
ok 224 did not get value
# test ignoring pairs with the wrong type
ok 225 no error
ok 226 no error
ok 227 got expected error
ok 228 did not get value
ok 229 got expected error
ok 230 did not get value
ok 231 got expected error
ok 232 did not get value
ok 233 got expected error
ok 234 did not get value
ok 235 got expected error
ok 236 did not get value
ok 237 got expected error
ok 238 did not get value
ok 239 got expected error
ok 240 did not get value
ok 241 got expected error
ok 242 did not get value
ok 243 got expected error
ok 244 did not get value
ok 245 got expected error
ok 246 did not get value
```

### PR DESCRIPTION
**Pull request by vweevers**
Closes #10. Should be rebased on top of #74.

### CODE REVIEW

File: level-ws.js [hunk 1]
```diff
@@ -63,11 +62,11 @@ WriteStream.prototype._flush = function (f) {
...
 
   function cb (err) {
-    if (err) {
-      self.emit('error', err)
-    } else {
-      if (f) f()
-      self.emit('_flush')
+    self._flushing = false
+
+    if (!self.emit('_flush', err) && err) {
```
Comment (ralphtheninja) [inline level-ws.js]: TIL about emit return values!

**Comment by vweevers** [comment]
Rebased. 🤞

**Comment by ralphtheninja** [comment]
@vweevers Epic implementation. Soooo nice to get rid of this thing now.
